
# **1. Basic Array Manipulation:**


Create a 1D array with values ranging from 0 to 9.


In [2]:
import numpy as np
array = np.arange(9)
print(array)

[0 1 2 3 4 5 6 7 8]


Reshape the array into a 3x3 matrix.

Explore Reshape Function

In [3]:
matrix = array.reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


Access the element at the second row, second column.


In [4]:
print(matrix[1:2,1:2])

[[4]]


Perform element-wise addition, subtraction, multiplication, and division on two arrays [1, 2, 3] and [4, 5, 6].


In [5]:
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])
print('Addition of two arrays is:')
print(array1+array2)
print('Subtraction of two arrays is:')
print(array1-array2)
print('Multiplication of two arrays is:')
print(array1*array2)
print('Division of two arrays is:')
print(array1/array2)

Addition of two arrays is:
[5 7 9]
Subtraction of two arrays is:
[-3 -3 -3]
Multiplication of two arrays is:
[ 4 10 18]
Division of two arrays is:
[0.25 0.4  0.5 ]


Find the sum, mean, and standard deviation of the array [1, 2, 3, 4, 5].


In [6]:
arraynew = np.array([1,2,3,4,5])
print('The sum of array is :')
print(np.sum(arraynew))
print('The mean of array is :')
print(np.mean(arraynew))
print('The standard deviation of array is :')
print(np.std(arraynew))

The sum of array is :
15
The mean of array is :
3.0
The standard deviation of array is :
1.4142135623730951


Reshape the array [1, 2, 3, 4, 5, 6] into a 2x3 array.

Explore Reshape

In [7]:
array = np.array([1, 2, 3, 4, 5, 6])
matrix = array.reshape(2,3)
print(matrix)

[[1 2 3]
 [4 5 6]]



# **2. Indexing and Slicing:**


Create a 5x5 array with random integers.


In [8]:
array = np.random.randint(0, 101, size=25)
matrix = array.reshape(5,5)
print(matrix)

[[ 46  60  25  30  71]
 [ 41   5   6  95  37]
 [ 15  59 100  79  67]
 [ 42  25  18  78  99]
 [ 23  63  34  50  82]]


Replace all values in the sub-array with a specific value.


In [9]:
subarray = matrix[1:4,1:4]
#subarray = 13 
matrix[1:4,1:4] = 13
print(subarray)
print('original matrix')
print(matrix)

[[13 13 13]
 [13 13 13]
 [13 13 13]]
original matrix
[[46 60 25 30 71]
 [41 13 13 13 37]
 [15 13 13 13 67]
 [42 13 13 13 99]
 [23 63 34 50 82]]


Extract the subarray [[3, 4], [7, 8]] from the array [[1, 2], [3, 4], [5, 6], [7, 8]].


In [21]:
array = np.array( [[1, 2], [3, 4], [5, 6], [7, 8]])
array
#print(array)
#print('Answer')
array[[1,3]]
#print(array[3:4,:])

array([[3, 4],
       [7, 8]])


# **3. Broadcasting:**

Create a 2D array of shape (3, 3) with values from 0 to 2.


In [24]:
array = np.arange(3)
array_2d = np.tile(array, (3,1))

print(array_2d)


[[0 1 2]
 [0 1 2]
 [0 1 2]]


Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.


In [55]:
array_1d = np.array([1, 2, 3])
print(array_1d+array_2d)

[[1 3 5]
 [1 3 5]
 [1 3 5]]


# **4. Concatenation and Splitting**


1.   Create two 2D arrays of shape (3, 3) with random integers.
2.   Concatenate them horizontally and vertically.
3.   Split the concatenated arrays back into the original arrays.


In [58]:
array1 = np.random.randint(0, 10, size=(3, 3))
array2 = np.random.randint(0, 10, size=(3, 3))
print('array 1:')
print(array1)
print('array 2:')
print(array2)

array 1:
[[9 2 5]
 [3 4 0]
 [0 3 4]]
array 2:
[[1 9 5]
 [4 3 7]
 [0 1 6]]


In [59]:
concatenated_horizontal = np.concatenate((array1, array2), axis=1)

concatenated_vertical = np.concatenate((array1, array2), axis=0)

print("Concatenated Horizontally:")
print(concatenated_horizontal)
print("Concatenated Vertically:")
print(concatenated_vertical)

Concatenated Horizontally:
[[9 2 5 1 9 5]
 [3 4 0 4 3 7]
 [0 3 4 0 1 6]]
Concatenated Vertically:
[[9 2 5]
 [3 4 0]
 [0 3 4]
 [1 9 5]
 [4 3 7]
 [0 1 6]]


In [63]:
split_horizontal = np.hsplit(concatenated_horizontal, 2)  
split_vertical = np.vsplit(concatenated_vertical, 2)  
print('split horizontally')
print(split_horizontal)
print('split vertically')
print(split_vertical)


split horizontally
[array([[9, 2, 5],
       [3, 4, 0],
       [0, 3, 4]]), array([[1, 9, 5],
       [4, 3, 7],
       [0, 1, 6]])]
split vertically
[array([[9, 2, 5],
       [3, 4, 0],
       [0, 3, 4]]), array([[1, 9, 5],
       [4, 3, 7],
       [0, 1, 6]])]


# **Bonus Question**

Find mode of this array  = [1,2,1,2,3,4,5,6,8,9,1,2,2,22,21,1,1,1,1,2,5]

Hint: Use count and also loop

In [29]:
array = np.array([1,2,1,2,3,4,5,6,8,9,1,2,2,22,21,1,1,1,1,2,5])
vals, counts = np.unique(array, return_counts=True)
print(vals)
print(counts)
mode_value = np.argwhere(counts == np.max(counts))
print(mode_value)
print(vals[mode_value].flatten().tolist())
print(np.max(counts))


[ 1  2  3  4  5  6  8  9 21 22]
[7 5 1 1 2 1 1 1 1 1]
[[0]]
[1]
7


# **Notes**


1.   All the Questions carry Equal Points (2 points)

2.   Bonus Question carry 5 points

3.   Review lecture for any query

Good Luck!

